### ISSUE TITLE
Design Review

### ISSUE THREAD

**Issue by TheDataAreClean** [The-Data-for-Children-Collaborative/noral-design-research#3]
> Review of the following tools:

- [x] Insight
- [x] SIMD
- [x] BGE Toolkit
- [x] NIF Interactive Evidence Report
- [x] SEEMIS
- [ ] SNSA
---

More tools to be added.

**Comment by jatinbaghel** [comment]
Hi @TheDataAreClean!
I have updated the Google Documents and MURAL Board for Insight Tool. Please go through them and share your feedback.

**Comment by TheDataAreClean** [comment]
@jatinbaghel Feedback:

- Update `null` to `<< TBD >>` for all documents.
- Mention all criterias of evalusation, even if they are not supported by the tool.

**Comment by TheDataAreClean** [comment]
**Next Steps**:

1. Finish SEEMIS and SNSA (If Recieved)
2. Go through Acorn Tool material for goof practices
3. Consoilidation (2 pager) of tool review learnings
> - Design Learnings
> - Feature Learnings
> - User Preferences

**Addtional Points**:
- Catch-up w/ Nupura
- Listen to Interviews
